### PR TITLE
Feat/delete quiz session

### PR DESCRIPTION
**Pull request by aprask**
### Changes

- Added a endpoint to delete quiz sessions.

### Gallery

_Before_
image

_Delete_
image

_After_
image

### CODE REVIEW

**Comment by AustinfHunter** [comment]
Looks good for the most part, however, I don't see any checks for ownership of the session. An instructor should not be able to delete sessions they didn't create. You should add a check for ownership (request.user.instructor should equal session.quiz.instructor) and return a 403 response if the check fails.

**Comment by aprask** [comment]
### Changes

- Added checker for ownership of the session

image
image

**Review by AustinfHunter — APPROVED** [review]
Looks good to me!

**Review by amhajja — APPROVED** [review]
This looks great!

**Pull request merged**
